### ISSUE TITLE
Hi man Speed Slow problem

### ISSUE THREAD

**Issue by HileYapak** [absoIute/Speedhack#2]
Hello, I used the code you gave
But I encountered a problem. I speed up the game. No problem. But the game freezes when it slows down again.
if (GetKeyState(VK_SHIFT) & 0x8000)
		{
			if (speedcontrol == true)
			{
				speedcontrol = false;
				multiplier =5.0f;
			}
		}else{
			if (speedcontrol==false)
			{
				speedcontrol = true;
				multiplier = 1.0f;
			}
		}

Codes may seem inexperienced sorry :) 
Can you tell me how to solve it?

**Comment by HileYapak** [comment]
Thanks I solved it myself

**Comment by decoder0007** [comment]
How did you solve this
